### ISSUE TITLE
Add an options page to allow users to configure how long their datatables state is saved for

### ISSUE THREAD

**Issue by tfrizzell** [tfrizzell/harnessnation-plus#1]
We're current setting `stateDuration` statically to 31557600 in our DataTables configuration modification to help ensure the state persists beyond a few hours. To provide users with a better experience, we should create an options page to allow users to select how long they want to state to persist for.

### Tasks
- [x]  Create an options page
- [x]  Provide an option to set the persistence timeout for tables on the **Main Stable** page
- [x]  Provide an option to set the persistence timeout for tables on the **Breeding Stable** page
- [x]  Provide an option to set the persistence timeout for tables in the **Progeny List** modal
- [x]  Update the existing content scripts to use the new settings
