### ISSUE TITLE
Add a stud fee calculator

### ISSUE THREAD

**Issue by tfrizzell** [tfrizzell/harnessnation-plus#3]
In tfrizzell/hn-plus-legacy we had a stud fee calculator with formulas created by Niek. We should re-implement this feature.

### Tasks
- [x] Add a button next to the breeding fee inputs on https://www.harnessnation.com/breeding/manage/stallions to allow the user to calculate their stud fee
- [X] ~~When the button is clicked, the following should happen:~~
    * ~~Check to see if the user has a preferred formula (see below) setting saved~~
    * ~~If the setting isn't saved, present popup with the formula (see below) options~~
- [x] Once a formula is selected, fetch the data and generate the stud fee

### Formulas
1. Apex Formula _(default)_
    * **Studs with no racing offspring:** Calculate their `average earnings per start` over the racing career and round to the nearest 1000
    * **Studs with racing offspring:** Take 25% of their `average earnings per starter` and round to the nearest 1000
2. Ridge Formula
    * **Studs with no racing offspring:** Calculate 5000 + 5 * `lifetime earnings` / 100 and round to the nearest 1000
    * **Studs with racing offspring:** Calculate 5000 + 5 * `average earnings per starter` / 10 and round to the nearest 1000
